# .github/workflows/setup_webserver.yml
name: Setup Web Server
on:
  push:
    branches: [ main ]
jobs:
  setup_server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Setup Script
      run: bash setup_webserver.sh
